blank_issues_enabled: false
contact_links:
  - name: Nous rejoindre sur Discord, pour toutes questions ou demandes
    url: https://discord.gg/FQt3GFHDd8
    about: Official Minecraft Launcher for World Nations server's
